AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    MemorySize: 1024
    Architectures: [!Ref LambdaArchitecture]
    Runtime: dotnet8
    Timeout: 30
    Tracing: Active
    Environment:
      Variables:
        REVENDA_TABLE_NAME: !Ref Table

Parameters:
  LambdaArchitecture:
    Type: String
    Default: x86_64
    AllowedValues:
      - arm64
      - x86_64
    Description: Enter arm64 or x86_64

Resources:
  CreateRevendaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./CreateRevenda/
      Handler: CreateRevenda::CreateRevenda.Function::FunctionHandler
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /revendas 
            Method: POST
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: dynamodb:PutItem
              Resource: !GetAtt Table.Arn

  GetRevendasFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./GetRevendas/
      Handler: GetRevendas::GetRevendas.Function::FunctionHandler
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /revendas
            Method: GET
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: dynamodb:Scan
              Resource: !GetAtt Table.Arn

  CreatePedidoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./CreatePedido/
      Handler: CreatePedido::CreatePedido.Function::FunctionHandler
      Environment:
        Variables:
          PROCESSAR_PEDIDOS_FUNCTION_NAME: !Ref ProcessarPedidosFunction
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /pedidos
            Method: POST
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
              Resource: !GetAtt Table.Arn
            - Effect: Allow
              Action: lambda:InvokeFunction
              Resource: !GetAtt ProcessarPedidosFunction.Arn

  ProcessarPedidosFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./ProcessarPedidos/
      Handler: ProcessarPedidos::ProcessarPedidos.Function::FunctionHandler
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /processar
            Method: POST
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:GetItem
                - dynamodb:Scan
              Resource: !GetAtt Table.Arn

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"